name: Build and Deploy Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site with prefix paths
        run: npm run build -- --prefix-paths

      - name: Copy .htaccess file
        run: cp ./.htaccess ./public/.htaccess

      - name: Deploy to Nexcess
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Using the private SSH key stored as a secret
          source: ./public/
          target: /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress
          rm: true
          debug: true
