name: Build and Deploy Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site with prefix paths
        run: npm run build -- --prefix-paths
        env:
          GATSBY_SITE_URL: https://5d43103688.nxcli.io/blog/

      - name: Deploy to Nexcess
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./public/
          target: /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/
          rm: false  # Prevents removing all files in the target directory
          overwrite: true  # Overwrites existing files without removing the .htaccess
          debug: true

      - name: Move files to correct location
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rsync -av --exclude '.htaccess' /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/public/ /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/
            rm -rf /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/public
