name: Build and Deploy Gatsby Site

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use a Node.js version compatible with Gatsby

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Gatsby site
      - name: Build Gatsby Site
        run: npm run build

      # Step 5: Deploy to Nexcess using SFTP
      - name: Deploy to Nexcess
        uses: appleboy/scp-action@v0.1.4
        with:
          host: cloudhost-70174.us-midwest-1.nxcli.net
          username: blog-admin@5d43103688.nxcli.io
          password: HippedCadsLacyDefine
          source: ./public/  # Gatsby builds static files into the "public" folder
          target: public_html/testwordpress/  # Directory where files should be uploaded
          rm: true  # Remove old files before uploading new ones
