name: Build and Deploy Gatsby Site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          npm install
          npm install sharp # Ensure sharp is installed for image processing
          
      - name: Clean Gatsby cache and public directory
        run: |
          npm run clean
          rm -rf .cache public
          
      - name: Build Gatsby site
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          GATSBY_CONCURRENT_DOWNLOAD: "5"
        run: |
          GATSBY_CPU_COUNT=1 npm run build -- --prefix-paths
          
      - name: Deploy to Nexcess
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./public/"
          target: "/chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/"
          rm: false
          overwrite: true
          strip_components: 1
          
      - name: Fix permissions
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod -R 755 /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/
            find /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/ -type f -exec chmod 644 {} \;
