name: Build and Deploy Gatsby Site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          npm install
          # Remove sharp installation since we're not processing images
          # npm install sharp
          
      - name: Clean Gatsby cache and public directory
        run: |
          npm run clean
          rm -rf .cache public
          
      - name: Build Gatsby site with prefix paths
        run: npm run build -- --prefix-paths
          
      - name: Deploy to Nexcess
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./public/"
          target: "/chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/"
          rm: false
          overwrite: true
          strip_components: 1
          
      - name: Fix permissions
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rsync -av --exclude '.htaccess' /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/public/ /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/
            rm -rf /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/public
