name: Manual Gatsby Site Build

on:
  repository_dispatch:
    types: [manual-build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site with prefix paths
        run: npm run build -- --prefix-paths

      - name: Deploy to Nexcess
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./public/
          target: /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/
          rm: true
          debug: true

      - name: Move files to correct location
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mv /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/public/* /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/
            rmdir /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress/public
