name: Manual Gatsby Site Build
on:
  repository_dispatch:
    types: [manual-build]  # Changed to match our manual trigger event type

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Cache Gatsby files
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'  # Enable built-in npm caching

      - name: Install dependencies
        run: npm ci  # Uses package-lock.json for faster, reliable installs

      - name: Build Gatsby site (optimized)
        run: |
          npm run build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true  # Enable incremental builds
          CI: true
          NODE_OPTIONS: "--max_old_space_size=4096"  # Increase memory limit

      - name: Deploy to Nexcess
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 5d43103688.nxcli.io
          username: afd62358_7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./public/
          target: /chroot/home/afd62358/5d43103688.nxcli.io/pub/blog/testwordpress
          rm: true
          strip_components: 1  # Remove the 'public' parent directory
          overwrite: true  # Overwrite existing files
